#!/bin/bash

find `pwd` \( -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' \) -exec grep -n "$@" {} \; -print | sed -e "s|^\(/.*\)$| `tput setaf 2`\1`tput setaf 7`|" | sed -e "s|^\([0-9][0-9]*\):|    `tput setaf 3`\1:`tput setaf 7`|"


