/*
 * Generated by dtrace(1M).
 */

#ifndef	_QUAKE_PROVIDER_H
#define	_QUAKE_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	QUAKE_CORE_LOOP_END() \
	__dtrace_quake___core_loop__end()
#ifndef	__sparc
#define	QUAKE_CORE_LOOP_END_ENABLED() \
	__dtraceenabled_quake___core_loop__end()
#else
#define	QUAKE_CORE_LOOP_END_ENABLED() \
	__dtraceenabled_quake___core_loop__end(0)
#endif
#define	QUAKE_CORE_LOOP_START() \
	__dtrace_quake___core_loop__start()
#ifndef	__sparc
#define	QUAKE_CORE_LOOP_START_ENABLED() \
	__dtraceenabled_quake___core_loop__start()
#else
#define	QUAKE_CORE_LOOP_START_ENABLED() \
	__dtraceenabled_quake___core_loop__start(0)
#endif
#define	QUAKE_SIM_PLAYERS(arg0) \
	__dtrace_quake___sim__players(arg0)
#ifndef	__sparc
#define	QUAKE_SIM_PLAYERS_ENABLED() \
	__dtraceenabled_quake___sim__players()
#else
#define	QUAKE_SIM_PLAYERS_ENABLED() \
	__dtraceenabled_quake___sim__players(0)
#endif
#define	QUAKE_SIM_TOTAL(arg0) \
	__dtrace_quake___sim__total(arg0)
#ifndef	__sparc
#define	QUAKE_SIM_TOTAL_ENABLED() \
	__dtraceenabled_quake___sim__total()
#else
#define	QUAKE_SIM_TOTAL_ENABLED() \
	__dtraceenabled_quake___sim__total(0)
#endif


extern void __dtrace_quake___core_loop__end(void);
#ifndef	__sparc
extern int __dtraceenabled_quake___core_loop__end(void);
#else
extern int __dtraceenabled_quake___core_loop__end(long);
#endif
extern void __dtrace_quake___core_loop__start(void);
#ifndef	__sparc
extern int __dtraceenabled_quake___core_loop__start(void);
#else
extern int __dtraceenabled_quake___core_loop__start(long);
#endif
extern void __dtrace_quake___sim__players(int);
#ifndef	__sparc
extern int __dtraceenabled_quake___sim__players(void);
#else
extern int __dtraceenabled_quake___sim__players(long);
#endif
extern void __dtrace_quake___sim__total(int);
#ifndef	__sparc
extern int __dtraceenabled_quake___sim__total(void);
#else
extern int __dtraceenabled_quake___sim__total(long);
#endif

#else

#define	QUAKE_CORE_LOOP_END()
#define	QUAKE_CORE_LOOP_END_ENABLED() (0)
#define	QUAKE_CORE_LOOP_START()
#define	QUAKE_CORE_LOOP_START_ENABLED() (0)
#define	QUAKE_SIM_PLAYERS(arg0)
#define	QUAKE_SIM_PLAYERS_ENABLED() (0)
#define	QUAKE_SIM_TOTAL(arg0)
#define	QUAKE_SIM_TOTAL_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _QUAKE_PROVIDER_H */
